use std::collections::HashSet;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use dialoguer::theme::ColorfulTheme;
use dialoguer::MultiSelect;

use crate::downloader::filename_from_url;
use crate::queue::Job;

/// Scans any text file for http/https links. Handles plain one-per-line lists,
/// "<url> <filename>" lines, and links embedded in surrounding text.
/// Duplicates are removed, order is preserved.
pub fn parse_link_file(path: &Path, dir: &Path) -> Result<Vec<Job>> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("reading link file {}", path.display()))?;

    let mut seen = HashSet::new();
    let mut jobs = Vec::new();

    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let mut tokens = line.split_whitespace();
        let Some(first) = tokens.next() else { continue };

        if is_link(first) {
            // Optional second token is a custom output filename.
            let name = tokens
                .next()
                .filter(|t| !is_link(t))
                .map(sanitize_name)
                .unwrap_or_else(|| filename_from_url(first));
            push(&mut jobs, &mut seen, first, name, dir);
            continue;
        }

        // Fall back to pulling every link out of a prose line.
        for token in std::iter::once(first).chain(tokens) {
            let token = token.trim_matches(|c: char| "\"'<>(),;".contains(c));
            if is_link(token) {
                let name = filename_from_url(token);
                push(&mut jobs, &mut seen, token, name, dir);
            }
        }
    }

    Ok(jobs)
}

fn push(jobs: &mut Vec<Job>, seen: &mut HashSet<String>, url: &str, name: String, dir: &Path) {
    if seen.insert(url.to_string()) {
        jobs.push(Job { url: url.to_string(), output: dir.join(name) });
    }
}

fn is_link(token: &str) -> bool {
    token.starts_with("http://") || token.starts_with("https://")
}

fn sanitize_name(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| if c == '/' || c == '\\' || c == '\0' { '_' } else { c })
        .collect();
    if cleaned.trim().is_empty() { "download.bin".to_string() } else { cleaned }
}

/// Checkbox window: space toggles a link, `a` toggles all, enter confirms.
/// Everything starts selected.
pub fn choose_jobs(jobs: Vec<Job>) -> Result<Vec<Job>> {
    if jobs.is_empty() {
        return Ok(jobs);
    }

    let labels: Vec<String> = jobs
        .iter()
        .map(|job| {
            let name = job
                .output
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_else(|| "download.bin".to_string());
            format!("{name}   <- {}", shorten(&job.url, 70))
        })
        .collect();

    let picked = MultiSelect::with_theme(&ColorfulTheme::default())
        .with_prompt("Select links to queue  (space = toggle, a = all, enter = confirm)")
        .items(&labels)
        .defaults(&vec![true; labels.len()])
        .report(false)
        .interact()?;

    let wanted: HashSet<usize> = picked.into_iter().collect();
    Ok(jobs
        .into_iter()
        .enumerate()
        .filter(|(i, _)| wanted.contains(i))
        .map(|(_, job)| job)
        .collect())
}

/// Writes the selection back out as a queue file that `rdm queue` can read.
pub fn write_queue_file(jobs: &[Job], path: &PathBuf) -> Result<()> {
    let mut out = String::from("# generated by rdm import\n");
    for job in jobs {
        let name = job.output.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
        out.push_str(&format!("{}\t{}\n", job.url, name));
    }
    std::fs::write(path, out).with_context(|| format!("writing queue file {}", path.display()))?;
    Ok(())
}

fn shorten(text: &str, max: usize) -> String {
    if text.chars().count() <= max {
        return text.to_string();
    }
    let head: String = text.chars().take(max / 2 - 2).collect();
    let tail: String = text.chars().skip(text.chars().count() - max / 2).collect();
    format!("{head}...{tail}")
}
